name: SonarCloud Analysis

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - feature/springboot-assignement

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Build with Maven
        run: mvn clean verify jacoco:report

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=Swetha-mp-03_SpringBootAssignment_sonar
            -Dsonar.organization=swetha-mp-03
            -Dsonar.host.url=https://sonarcloud.io
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
